### ISSUE TITLE
Error rendering slope graphs in Firefox

### ISSUE THREAD

**Issue by kompike** [datavisyn/lineupjs#18]
Hi there. I'm using LineUp.js library to display statistics for large data and connections between separate rankings. It works fine in Google Chrome but throws an error in Firefox (version 60.0.1):

![image](https://user-images.githubusercontent.com/12595844/41046980-30f77974-69b4-11e8-9bd3-0ff87d58c4e8.png)

In this way it renders all the rankings but without connections between them.

### Steps to reproduce

 1. Open LineUp with slope graphs in Firefox(version 60.0.1) browser.

### Observed behavior
 * Connections between rankings are not rendered.
 * `TypeError: g.ownerSVGElement is undefined` is thrown.

### Expected behavior
 * LineUp renders all rankings with connections between them

**Comment by sgratzl** [comment]
@kompike please make sure that you are using the latest version `3.0.1-beta.13`

**Comment by sgratzl** [comment]
please reopen with a faulty example, cause I cannot reproduce it as described before
