### ISSUE TITLE
How to use lineupjs by es6 import?

### ISSUE THREAD

**Issue by crcrcry** [datavisyn/lineupjs#21]
* Release number or git hash: 3.0.1-beta.13
 * Web browser version and OS: macos 10.13.3 chrome 67

### Steps to reproduce
1. `npm install --save lineupjs@next`
2. 
```javascript
import LineUpJS from 'lineupjs';
import 'lineupjs/build/LineUpJS.css'

const arr = []
for (let i = 0; i < 100; i++) {
  arr.push({
    attr1: Math.random() * 10,
    attr2: Math.random() * 10,
    attr3: Math.random() * 10,
  })
}
LineUpJS(document.body, arr)
```

### Observed behavior
Chrome dev tool consoles errors:
![wx20180613-194819](https://user-images.githubusercontent.com/19330440/41349725-64961d00-6f43-11e8-8864-5e934075bfed.png)

### Expected behavior
 *

**Comment by sgratzl** [comment]
the default export is the LineUp class not a factory function. please use

```
LineUpJS.asLineUp(document.body, arr)
```

**Comment by crcrcry** [comment]
Thank you very much!!
