### ISSUE TITLE
Is there an API document?

### ISSUE THREAD

**Issue by crcrcry** [datavisyn/lineupjs#22]
- I wonder if there is an API document, which could help developers write callback function for interaction.
- For example: I want to pass a callback function to lineup component. When the cursor hovers a row in lineup, the callback function could get the data of this row and do something else. 
- This [docs](https://lineup.js.org/master/docs/) is hard to read and understand.

**Comment by sgratzl** [comment]
I usually use TypeScript and rely on the auto completion features of every editor then :). 

like I type 
```
const lineup = asLineUp(...);
lineup.
```
and my editor (like visual studio code) lists all available methods including the `on` method and static constants.

**Comment by crcrcry** [comment]
Thank you, it solved my problem. 
However, I still think you could improve the document. If you write the document like [d3](https://d3js.org/) and reduce the development difficulty, more people are absolutely willing to use such an excellent visualization tool.

**Comment by thinkh** [comment]
@crcrcry Have you seen the [API documentation](https://lineup.js.org/master/docs/)? You can find the different class documentations to the right.

**Comment by sgratzl** [comment]
thx. We know that the weakest part of the library is its documentation. For sure not its features :-)

**Comment by sgratzl** [comment]
moved to #23
