### ISSUE TITLE
support for multiple rankings in the side panel

### ISSUE THREAD

**Issue by sgratzl** [datavisyn/lineupjs#43]
in the current version the summaries + chooser + add sorting hierarchy just operated on the first ranking. 

A possible approach would be to use a tabbing for switch between different rankings

**Comment by thinkh** [comment]
Yes, I agree that a tabbing would be the best solution for now. This would include the grouping/sorting hierarchy (#41) and the available columns.

**Comment by sgratzl** [comment]
I would use a similar approach as the browsers, too, go to the right + a dropdown on the right side for direct access. 

Tho individual rankings doesn't have a name or label, thus what is the label?

**Comment by thinkh** [comment]
I assume the default name is `Ranking 1`, `Ranking 2`, etc. However, it would be nice if the user can rename the ranking to something more meaningful.

**Comment by thinkh** [comment]
Done with PR #44.
