### ISSUE TITLE
Scrollbars are shown in each cell

### ISSUE THREAD

**Issue by lehnerchristian** [datavisyn/lineupjs#51]
* Release number or git hash: v3.1
 * Web browser version and OS: Firefox Developer Edition, Firefox on Ubuntu 18.04

### Steps to reproduce

 1. Open LineUp in Firefox (e.g. https://codepen.io/sgratzl/pen/vppyML)
 

### Observed behavior
 * Scrollbars are shown in almost each cell

### Expected behavior
 * Cells should not have a scrollbar

### Possible Reason
* After investigating with @sgratzl a possible reason for this is that the user-agent stylesheet of Firefox defines 19px line-height by default. With 18px line height the scrollbars would be gone.

**Comment by sgratzl** [comment]
can you try to set the line-height of a row or cell to `line-height: 100%`?

**Comment by lehnerchristian** [comment]
both didn't solve the issue for me:
![screenshot from 2018-08-16 12-35-22](https://user-images.githubusercontent.com/1711080/44203893-f4b8af80-a150-11e8-89bb-a0e3e7dbe3f4.png)

**Comment by lehnerchristian** [comment]
When I open the CodePen from above (https://codepen.io/sgratzl/pen/vppyML) I don't see the scrollbars anymore
The line-height seems to be 19px now

**Comment by lehnerchristian** [comment]
In my local app I still experience the issue, but I probably need to update my LineUp version?

**Comment by sgratzl** [comment]
cannot reproduce, increasing the row height can be a workaround.
