### ISSUE TITLE
Unselecting all categories doesn't always remove all the items

### ISSUE THREAD

**Issue by katush** [datavisyn/lineupjs#53]
Unselecting all categories doesn't remove all the items from the table: 

![1](https://user-images.githubusercontent.com/8986080/43576356-71c955f0-9649-11e8-87b8-4c8adc3bdf8c.gif)

**Comment by sgratzl** [comment]
what is the usecase for removal all rows?

**Comment by katush** [comment]
I agree that it doesn't have much use, but that is I expect to happen when I filter out everything... otherwise people think the filtering doesn't work -> inconsistent behavior.
