### ISSUE TITLE
Setting weights in combined columns not working intuitively

### ISSUE THREAD

**Issue by katush** [datavisyn/lineupjs#54]
Workflow:
Combine Age and Height columns, then change the weight of age to 60% and confirm (leave height at 50%).
Resulting weights are 54.5% and 45.5%.

I know this is the result of proportional scaling of the 60+50%  to a total of 100%, but everyone who tried it when playing with the tool was confused by this and expected that only the "other" weight would be adjusted - i.e. if you set 60% to age, then height would automatically change to 40%.

**Comment by sgratzl** [comment]
what should happen if there are more than 2 columns?

**Comment by katush** [comment]
The remaining ones should be adjusted proportionally, that's what I would expect at least.

**Comment by sgratzl** [comment]
current dev version: 

![combined2](https://user-images.githubusercontent.com/4129778/48550359-cd4dbc00-e8d2-11e8-9c63-3d8fdaa21f2a.gif)
