### ISSUE TITLE
Rename Sort Group by...

### ISSUE THREAD

**Issue by katush** [datavisyn/lineupjs#56]
People had trouble finding the group sorting option (even though I demonstrated this in the introduction part) and tended to overlook it when searching for it in column menu. When asked why they skipped this option and searched for the solution under "Filter" or "Visualization" they answered they were not sure what "Sort Group by..." would do. Some users also expected this option to be found somewhere around grouping hierarchy panel or in group column.

At the very least it should be renamed to  Sort Groups by... (add 's') but maybe someone has some better idea of how to make it more indicative of the functionality it offers?

**Comment by thinkh** [comment]
The menu item is already renamed to `Sort Groups by...`

![image](https://user-images.githubusercontent.com/5851088/45301883-246d9400-b512-11e8-9796-0ecca1feafa3.png)

I'm not sure how we should further proceed here. For me it does not make sense to move this function to *Filter* or *Visualization*.

**Comment by katush** [comment]
No, I agree it doesn't make sense to move it there (I was merely commenting on the fact that people tended to overlook it and searched elsewhere...). Maybe it was just confusing because without the 's' people thought it was sorting "within" rather than "between" groups. I don't know how to make this any more clear though, so I would just keep it as it is now.

**Comment by thinkh** [comment]
Ok, thanks for your clarification. I will close this issue. We can re-open it or open a new one, if we have a better idea.
