### ISSUE TITLE
When the matrix is split, it is no longer possible to sort by the whole matrix

### ISSUE THREAD

**Issue by katush** [datavisyn/lineupjs#57]
When the matrix is split, it is no longer possible to sort by the whole matrix - clicking the sort button on the main matrix header will result into sorting by it's first column:
![image](https://user-images.githubusercontent.com/8986080/43579572-da67cc6e-9652-11e8-891b-6a47540b5afc.png)

**Comment by sgratzl** [comment]
splitting matrix is not a feature of lineupjs. please report this bug at https://github.com/Caleydo/lineup_app
