### ISSUE TITLE
Changing histogram when filtering

### ISSUE THREAD

**Issue by katush** [datavisyn/lineupjs#60]
Most people in the study complained that the histogram in filter panel changes when filtering and they lose a reference of how much of the original data they filtered out.
Suggested behavior: keep the histogram in the filter panel fixed - only the histogram in the column header should indicate the distribution of the currently displayed.

**Comment by sgratzl** [comment]
current dev version:

![filter](https://user-images.githubusercontent.com/4129778/48550157-3bde4a00-e8d2-11e8-91e7-7bc770d43a8b.gif)

**Comment by mstreit** [comment]
This is a very nice improvement!
