### ISSUE TITLE
Filtering matrix by histogram doesn't work

### ISSUE THREAD

**Issue by katush** [datavisyn/lineupjs#68]
Filtering matrix by histogram doesn't work:
![4](https://user-images.githubusercontent.com/8986080/43582553-20f26f18-965d-11e8-989c-eefad63b3d1a.gif)

**Comment by mstreit** [comment]
We have not defined yet what the behavior should be. 
Option 1: Filter by average value
Option 2: Remove filter option for matrix data (short term solution)
@sgratzl, what do you think?

**Comment by katush** [comment]
This seems to be working now, @sgratzl @thinkh, correct?

**Comment by mstreit** [comment]
Yes, it sorts the matrix by the mean value. Thanks @sgratzl.
