### ISSUE TITLE
Dataset disappears when "Proportional symbol" vis selected

### ISSUE THREAD

**Issue by katush** [datavisyn/lineupjs#81]
Dataset disappears when "Proportional symbol" vis selected
Steps to reproduce

 1. Load any dataset
 1. Switch item visualization of numerical column to Proportional symbol
![propsymbol](https://user-images.githubusercontent.com/8986080/46599251-126a1b80-cae7-11e8-9fd6-f99fa1338241.gif)

**Comment by sgratzl** [comment]
fixed in https://github.com/datavisyn/lineupjs/commit/a889ce548cab6a6c967007fe03601701b41d6395#diff-8982e6863f958abb4d030707c708d487
