### ISSUE TITLE
remove color of a column?

### ISSUE THREAD

**Issue by sgratzl** [datavisyn/lineupjs#82]
in the original lineup the color of a column was used as background for the column header to better separate them. This was removed in the js version by using icons for different types. The only application was as the color of the bars in numerical values. However, with introducing the recent color mapping feature the color was just used as default. 

Thus the coloring can be removed by default.

**Comment by thinkh** [comment]
Yes, I think we can remove the colum color.

**Comment by mstreit** [comment]
Yep.
The new color mapping dialog is really cool btw.
