### ISSUE TITLE
Import does not load previously exported dataset

### ISSUE THREAD

**Issue by mstreit** [datavisyn/lineupjs#83]
* Release number or git hash: public soccer demo
 * Web browser version and OS: Chrome

### Steps to reproduce

 1. Open soccer dataset
 2. Export CSV
 3. Import the previously exported CSV

Similar problems when exporting and importing JSON.

### Observed behavior
 * Only loading bar is shown

### Expected behavior
 * Dataset should appear in LineUp

**Comment by sgratzl** [comment]
Issue moved to [datavisyn/lineup_app #31](https://github.com/datavisyn/lineup_app/issues/31) via [**ZenHub**](https://www.zenhub.com/)
