### ISSUE TITLE
How to prune visualization options?

### ISSUE THREAD

**Issue by thinkh** [datavisyn/lineupjs#88]
* Release number or git hash: 4.0.0-alpha.3
 * Web browser version and OS: Chrome 

I want to remove/disable some options from the visualization sub-menu (see [detailed description](https://github.com/Caleydo/lineup_app/issues/33)). After checking the code I'm not sure how to do that. 

All available renderers are listed in [src/renderer/index.ts](https://github.com/datavisyn/lineupjs/blob/develop/src/renderer/index.ts). However, each renderer class has a [`canRender()` function](https://github.com/datavisyn/lineupjs/blob/24d1abc18ee2b99deb091980792e17f21c782edd/src/renderer/interfaces.ts#L116) and decides, e.g., based on the column type if it can/will render the data. 

I could not figure out how to modify the renderer list from outside (i.e., without touching each renderer in the library). Is there another way?

**Comment by sgratzl** [comment]
is an open issue, see https://github.com/datavisyn/lineupjs/blob/master/src/renderer/index.ts#L104

**Comment by sgratzl** [comment]
see 

https://github.com/datavisyn/lineupjs/blob/47246adbc2bdbb8333a4b68e8e5014b4a442892b/src/interfaces.ts#L148-L151

**Comment by thinkh** [comment]
Thanks @sgratzl. I implemented it [here](https://github.com/Caleydo/lineup_app/pull/34/files) and it works well. However, I had to use the title of the renderer, as the renderer classes itself are not exposed in the API. Hence, I could not import these classes and check them with `renderer instanceof TableCellRenderer`.
In my opinion, this is a bit fragile, as the title stings of the renderer might change. Is it possible to make the renderer classes also public or do you know any other robust way?

**Comment by sgratzl** [comment]
I changed the interface to
```
/** 
    * custom check whether a given renderer can render the given column in the given mode 
    */ 
   canRender: (type: string, renderer: ICellRendererFactory, col: Column, mode: ERenderMode) => boolean; 
```

**Comment by thinkh** [comment]
Thanks, that makes my life easier. 👍
