### ISSUE TITLE
advanced date column

### ISSUE THREAD

**Issue by sgratzl** [datavisyn/lineupjs#98]
so far the date column doesn't provide a lot of functionality

possible features
 * filter: date range or similar to number a date histogram
 * group: define granularity like (1m, 1y, 10y, 10d, ...) -> e.g. group by year, maybe even using the circular pattern (like group by quarter, group by weekday regardless of the week, ...)

**Comment by thinkh** [comment]
Maybe you can also take this issues into account https://github.com/Caleydo/lineupjs/issues/524.
