### ISSUE TITLE
Setting the weights of combined column not working

### ISSUE THREAD

**Issue by katush** [datavisyn/lineupjs#99]
It is now impossible to set weights for combined columns - the dialogue only shows the content of the column. Setting the weights by changing the width is also difficult ¨dragable¨ area is too small.

![weights](https://user-images.githubusercontent.com/8986080/47852738-ff442600-dddc-11e8-9d60-10fae774b83b.gif)

Related to this issue - https://github.com/datavisyn/lineupjs/issues/54

**Comment by sgratzl** [comment]
current dev version:
![combined](https://user-images.githubusercontent.com/4129778/48550343-c2932700-e8d2-11e8-909d-68cdac6fda81.gif)
